#! /usr/bin/env bash

# Meant to simply deploying the containers under docker-files
# Single launch point to simplify importing config

VALID_CONTAINERS=$(ls -1 docker-files/ | sed -e 's/\.sh$//')

CONTAINER_TO_RUN=$1
if [ ! -f "docker-files/$1.sh" ]; then
   # Error
   echo "Unable to find 'docker-files/$CONTAINER_TO_RUN.sh', please create and try again"
   exit 1
else
   # Import config
   CONFS="eclectic-docker-common.conf conf.d/$CONTAINER_TO_RUN.conf"
   for c in $CONFS ; do
      if [ -f "conf.d/$c" ]; then
         . conf.d/$c
         echo "Running $CONTAINER_TO_RUN:"
         ./docker-files/$CONTAINER_TO_RUN.sh
      else
         echo "Missing config: $c, please configure according to samples"
         exit 1
      fi
   done
fi

